services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    

  backend:
    build:
      context: ./backend
    image: open-data-statistics-backend
    volumes:
      - ./backend:/app
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  worker:
    build:
      context: ./backend
    image: open-data-statistics-worker
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    command: ["celery", "-A", "app.worker:app", "worker", "--loglevel=info","--concurrency=1"]
    extra_hosts:
      - 'host.docker.internal:host-gateway'